title: "Investment Research"
description: "Research notes and watchlists (not financial advice)."
url: "https://michaelmu.github.io"
baseurl: "/investment-research"

theme: minima

# custom styling
sass:
  sass_dir: assets/css
  style: compressed

collections:
  companies:
    output: true
    permalink: /companies/:name/

defaults:
  - scope:
      path: ""
      type: "companies"
    values:
      layout: page

plugins:
  - jekyll-feed

exclude:
  - README.md
  - vendor
